spring:
  application:
    name: wallet-service  # the same with com.yiqiniu.easytrans.demos.order.Constant.APPID
  datasource: # order service datasource config
    url: jdbc:mysql://localhost:3306/wallet?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8081
 
# RIBBON用，也可以直接开启Eureka
order-service:
  ribbon:
    listOfServers: localhost:8080

wallet-service:
  ribbon:
    listOfServers: localhost:8081

easytrans:
  master:
    zk:
      zooKeeperUrl: localhost:2281
  stringcodec:
    zk:
      zooKeeperUrl: ${easytrans.master.zk.zooKeeperUrl}
  idgen:
    trxId:
      zkSnow:
        zooKeeperUrl: ${easytrans.master.zk.zooKeeperUrl}
  log:
    database:
      logCleanEnabled: true
      logReservedDays: 14
      logCleanTime: 01:22:00
      druid:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/wallet_translog?characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456




    
      